version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workarea
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./solutions:/workarea/solutions
    command: python -m unittest discover --verbose

volumes:
  solutions:
  _posts: